name: Deploy to Stage
on:
  push:
    branches:
      - main

jobs:
  redeploy:
    name: Redeploy to Stage
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H stage.mono.yogeshkumar.me >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa yogesh@stage.mono.yogeshkumar.me "source ~/.bashrc && cd next-mono/ && git pull --no-tags --force && pnpm install --frozen-lockfile && pnpm build && pm2 restart all"
