name: Deploy to Stage
on:
  push:
    branches:
      - main

jobs:
  redeploy:
    name: Redeploy to Stage
    runs-on: ubuntu-latest
    steps:
      - name: SSH into the server and deploy
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          ssh -i ~/ssh_key root@stage.mono.yogeshkumar.me
          cd next-mono/ && git pull
          pnpm install
          pnpm build
          pm2 restart all
